# Необходимо заполнить файла конфига перед тестами
# Введите в поля информацию о сервере, приборе и креды пользователя (для доступа на сервер по SSH)


# Server configuration
server:
  host:            #имя сервера или ip (str)
  port:            #номер порта (int)

# User credentials
user:
  username:          #имя пользователя 
  password:          #пароль 

# Device info
device:
  name:          #название прибора
  sn:            #серийный номер

# Labview connection
Labview_client:
  host: 
  port: 